### ISSUE TITLE
discussion: Member와 그룹, 운동 통계 기능을 어떻게 연결할 지 의논이 필요

### ISSUE THREAD

**Issue by rdme0** [kakao-tech-campus-2nd-step3/Team17_BE#31]
## 설명
![image](https://github.com/user-attachments/assets/8af99b51-a17d-4f85-907b-8443d29e4917)
이 api를 구현하기 위하여 그룹 기능과, 운동리스트 기능을 어떻게 연결할 지 의논이 필요함

**Comment by Woojae-Jeong** [comment]
운동 기능 : 서비스 계층에서 운동 통계 기능 구현
그룹 기능 : 서비스 계층에서 본인이 속한 그룹을 조회할 수 있는 기능 구현
