### ISSUE TITLE
discussion: 원시값을 포장하는 VO 클래스를 record 클래스로 정의

### ISSUE THREAD

**Issue by cliant** [kakao-tech-campus-2nd-step3/Team17_BE#48]
## 설명

저희가 현재 VO 클래스가 일반 class로 작성되어 있는데 이를 record로 통일하는게 어떨까 싶습니다

> 원시값을 포장하는 클래스(VO, Value Object)를 record로 작성하는 것은 매우 적절한 선택입니다. record는 불변성을 제공하고 간결한 구문으로 equals, hashCode, toString을 자동으로 생성해 주기 때문에 원시값 포장에 필요한 기능을 대부분 알아서 처리해줍니다.
>record는 본래 값 중심의 클래스를 표현하기 위해 도입되었으며, 원시값 포장 클래스는 바로 이 목적에 부합합니다. 예를 들어, Memo 또는 Email 같은 VO를 record로 작성하면 다음과 같은 장점이 있습니다:
>불변성: record는 필드가 자동으로 final로 선언되므로, 생성 이후 값을 변경할 수 없습니다.
>간결성: VO에 필요한 생성자, getter, equals, hashCode, toString 메서드를 자동으로 생성해주기 때문에 코드를 간결하게 유지할 수 있습니다.
>유효성 검사: record에서도 생성자 안에서 유효성 검사를 추가할 수 있습니다.

**Comment by hxunsc** [comment]
vo는 record로 통일하기로 결정
