### ISSUE TITLE
discussion: 운동 시작, 종료 엔드포인트 설정

### ISSUE THREAD

**Issue by hxunsc** [kakao-tech-campus-2nd-step3/Team17_BE#50]
## 설명
기존 API 명세서에서는 운동 시작은 `GET`, 종료는 `PUT`, 두 개의 엔드포인트를 동일했습니다. week3 리뷰에서 우재님이 언급하신 것처럼 저도 운동 시작도 `PUT` 요청이 맞다고 생각하여 `PUT`으로 수정했습니다!
그러다보니, 시작, 종료의 엔드포인트가 동일하다보니 에러가 발생하였고,
우선은 임시적으로 다음과 같이 변경해두었습니다.

- 운동 시작: "/api/exercise/{exerciseId}/start" 
- 운동 종료: "/api/exercise/{exerciseId}/stop"

그래서 이 부분에 대해서 논의해봐야할 것 같습니다!

**Comment by Woojae-Jeong** [comment]
메소드를 `post`와 `put`으로 변경토록
