### ISSUE TITLE
bug: 운동리스트 기능 버그 발견

### ISSUE THREAD

**Issue by rdme0** [kakao-tech-campus-2nd-step3/Team17_BE#57]
## 설명
운동리스트 컨트롤러에 `@Autowired`가 안되어 있고, 레포지터리에 `@Repository` 누락되어 있습니다.
그리고 `ExerciseListRepository`에 메서드 이름이 JPA가 알아볼 수 없는 이름이라 에러 뜨는 것 같습니다.

![image](https://github.com/user-attachments/assets/3b347372-aa06-4a4d-8489-38323e27742a)

**Comment by hxunsc** [comment]
- `ExerciseListRepository` 관련 버그 수정하였습니다! pr 확인부탁드려요!
    - 우선, 조회 기준 시간을 startTime으로 하도록 수정했는데, startTime으로 하면 문제가 발생할 수도 있을 것 같다는 생각이 들어서.. 해당 이슈 추가해두겠습니다~!!😀
- 컨트롤러에 `@Autowired` 는 사용하지 않아도 의존성 주입이 되고, 있는 것과 없는 것 동일하게 작동하는 것으로 알고 있는데 명시적인 효과때문에 추가해야한다고 하셨을까요?
