### ISSUE TITLE
discussion: DTO에 대한 원시값 포장 논의

### ISSUE THREAD

**Issue by cliant** [kakao-tech-campus-2nd-step3/Team17_BE#64]
## 설명
DTO에 대한 원시값 포장을 일괄적으로 할지, 일괄적으로 하지 않을지, 부분적으로 사용할지 논의 필요

>일관성을 중요시하고 도메인 규칙을 강제하고 싶다면, DTO에도 원시값 포장을 적용하는 것이 좋습니다. 이렇게 하면 도메인 로직과 데이터를 일관되게 처리할 수 있습니다.
>성능 최적화와 단순함을 중시한다면, DTO에는 원시값 포장을 생략하고, 기본적인 String, int 등의 원시 타입을 사용할 수 있습니다. 이 경우, 엔티티로 변환할 때만 원시값 포장을 적용하면 됩니다.

**Comment by Woojae-Jeong** [comment]
DTO에서 유효성 검사를 한다. 그리고 VO에서의 유효성 검사는 요청으로 인해 들어온 데이터에 대한 검사가 아닌 내부적으로 생성되는 데이터에 대한 유효성 검사이다.
